# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reduplications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reduplication',
            old_name='change_data',
            new_name='change_date',
        ),
    ]
