# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reduplications', '0002_auto_20170507_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduplication',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reduplications.ReduplicationCategory'),
        ),
        migrations.AlterField(
            model_name='reduplication',
            name='types',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
