# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduplications', '0003_auto_20170507_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reduplication',
            name='types',
        ),
        migrations.AddField(
            model_name='reduplication',
            name='types',
            field=models.ManyToManyField(to='reduplications.ReduplicationType'),
        ),
    ]
